"""initial schema

Mirrors openlibrary_schema.sql 1:1. Hand-written rather than autogenerated
because autogenerate misses MySQL-specific details (BIGINT UNSIGNED, JSON,
ENUM, `request_date DEFAULT (CURRENT_DATE)`).

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-09
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ts() -> sa.Column:
    return sa.Column(
        "created_at", mysql.TIMESTAMP, nullable=False,
        server_default=sa.text("CURRENT_TIMESTAMP"),
    )


def _ts_updated() -> sa.Column:
    return sa.Column(
        "updated_at", mysql.TIMESTAMP, nullable=False,
        server_default=sa.text("CURRENT_TIMESTAMP"),
        server_onupdate=sa.text("CURRENT_TIMESTAMP"),
    )


def upgrade() -> None:
    op.create_table(
        "authors",
        sa.Column("author_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("openlibrary_author_key", sa.String(32), nullable=False),
        sa.Column("author_name", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(255)),
        sa.Column("birth_date", sa.String(64)),
        sa.Column("bio", sa.Text),
        sa.Column("alternate_names", mysql.JSON),
        sa.Column("top_subjects", mysql.JSON),
        sa.Column("work_count", mysql.INTEGER(unsigned=True)),
        sa.Column("author_raw", mysql.JSON),
        _ts(), _ts_updated(),
        mysql_engine="InnoDB",
    )

    op.create_table(
        "books",
        sa.Column("book_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("openlibrary_work_key", sa.String(32), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("subtitle", sa.String(500)),
        sa.Column("description", sa.Text),
        sa.Column("first_publish_year", mysql.SMALLINT(unsigned=True)),
        sa.Column("first_publish_date", sa.String(64)),
        sa.Column("subjects", mysql.JSON),
        sa.Column("places", mysql.JSON),
        sa.Column("series", mysql.JSON),
        sa.Column("links", mysql.JSON),
        sa.Column("excerpts", mysql.JSON),
        sa.Column("cover_ids", mysql.JSON),
        sa.Column("cover_edition_key", sa.String(32)),
        sa.Column("work_raw", mysql.JSON),
        _ts(), _ts_updated(),
        mysql_engine="InnoDB",
    )

    op.create_table(
        "book_authors",
        sa.Column("book_id", mysql.BIGINT(unsigned=True), primary_key=True),
        sa.Column("author_id", mysql.BIGINT(unsigned=True), primary_key=True),
        sa.Column("author_order", mysql.SMALLINT(unsigned=True)),
        sa.Column("role_name", sa.String(128)),
        sa.ForeignKeyConstraint(["book_id"], ["books.book_id"],
                                name="fk_book_authors_book", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["author_id"], ["authors.author_id"],
                                name="fk_book_authors_author", ondelete="RESTRICT"),
        mysql_engine="InnoDB",
    )

    op.create_table(
        "editions",
        sa.Column("edition_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("openlibrary_edition_key", sa.String(32), nullable=False),
        sa.Column("book_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("subtitle", sa.String(500)),
        sa.Column("by_statement", sa.String(500)),
        sa.Column("publish_date", sa.String(64)),
        sa.Column("number_of_pages", mysql.INTEGER(unsigned=True)),
        sa.Column("languages", mysql.JSON),
        sa.Column("publishers", mysql.JSON),
        sa.Column("isbn_10", sa.String(20)),
        sa.Column("isbn_13", sa.String(20)),
        sa.Column("lccn", sa.String(64)),
        sa.Column("oclc", sa.String(64)),
        _ts(), _ts_updated(),
        sa.ForeignKeyConstraint(["book_id"], ["books.book_id"],
                                name="fk_editions_book", ondelete="CASCADE"),
        mysql_engine="InnoDB",
    )

    op.create_table(
        "members",
        sa.Column("member_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("member_code", sa.String(32), nullable=False),
        sa.Column("member_name", sa.String(255), nullable=False),
        sa.Column("gender", sa.Enum("male", "female", "other", "unknown", name="member_gender"),
                  nullable=False, server_default=sa.text("'unknown'")),
        sa.Column("dob", sa.Date),
        sa.Column("nationality", sa.String(128)),
        sa.Column("phone", sa.String(32)),
        sa.Column("email", sa.String(255)),
        sa.Column("address", sa.String(500)),
        sa.Column("registration_date", sa.Date, nullable=False),
        sa.Column("status", sa.Enum("active", "inactive", "blocked", name="member_status"),
                  nullable=False, server_default=sa.text("'active'")),
        _ts(), _ts_updated(),
        mysql_engine="InnoDB",
    )

    op.create_table(
        "copies",
        sa.Column("copy_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("edition_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("barcode", sa.String(64), nullable=False),
        sa.Column("call_number", sa.String(128)),
        sa.Column("acquisition_date", sa.Date),
        sa.Column("condition_status",
                  sa.Enum("new", "good", "fair", "damaged", "lost", name="copy_condition"),
                  nullable=False, server_default=sa.text("'good'")),
        sa.Column("circulation_status",
                  sa.Enum("available", "on_loan", "reserved", "lost", "repair", name="copy_circulation"),
                  nullable=False, server_default=sa.text("'available'")),
        sa.Column("shelf_location", sa.String(128)),
        sa.Column("notes", sa.String(500)),
        _ts(), _ts_updated(),
        sa.ForeignKeyConstraint(["edition_id"], ["editions.edition_id"],
                                name="fk_copies_edition", ondelete="RESTRICT"),
        mysql_engine="InnoDB",
    )

    op.create_table(
        "users",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("username", sa.String(64), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="user_role"),
                  nullable=False, server_default=sa.text("'USER'")),
        sa.Column("email", sa.String(255)),
        sa.Column("member_id", mysql.BIGINT(unsigned=True)),
        _ts(), _ts_updated(),
        sa.UniqueConstraint("username", name="uq_users_username"),
        sa.ForeignKeyConstraint(["member_id"], ["members.member_id"],
                                name="fk_users_member", ondelete="SET NULL"),
        mysql_engine="InnoDB",
    )

    op.create_table(
        "loans",
        sa.Column("loan_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("member_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("copy_id", mysql.BIGINT(unsigned=True)),
        sa.Column("requested_book_id", mysql.BIGINT(unsigned=True)),
        sa.Column("request_date", sa.Date, nullable=False,
                  server_default=sa.text("(CURRENT_DATE)")),
        sa.Column("borrow_date", sa.Date),
        sa.Column("due_date", sa.Date),
        sa.Column("return_date", sa.Date),
        sa.Column("renew_count", mysql.TINYINT(unsigned=True),
                  nullable=False, server_default=sa.text("0")),
        sa.Column("approval_status",
                  sa.Enum("PENDING", "APPROVED", "REJECTED", "RETURNED", "CANCELLED",
                          name="loan_approval_status"),
                  nullable=False, server_default=sa.text("'PENDING'")),
        sa.Column("loan_status",
                  sa.Enum("open", "returned", "overdue", "lost", name="loan_physical_status"),
                  nullable=False, server_default=sa.text("'open'")),
        sa.Column("fine_amount", sa.DECIMAL(12, 2),
                  nullable=False, server_default=sa.text("0.00")),
        sa.Column("approved_by_id", mysql.BIGINT(unsigned=True)),
        sa.Column("notes", sa.String(500)),
        _ts(), _ts_updated(),
        sa.ForeignKeyConstraint(["member_id"], ["members.member_id"],
                                name="fk_loans_member", ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["copy_id"], ["copies.copy_id"],
                                name="fk_loans_copy", ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["requested_book_id"], ["books.book_id"],
                                name="fk_loans_requested_book", ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["approved_by_id"], ["users.user_id"],
                                name="fk_loans_approver", ondelete="SET NULL"),
        mysql_engine="InnoDB",
    )
    op.create_index("idx_loans_member", "loans", ["member_id"])
    op.create_index("idx_loans_copy", "loans", ["copy_id"])
    op.create_index("idx_loans_requested_book", "loans", ["requested_book_id"])
    op.create_index("idx_loans_approval_status", "loans", ["approval_status"])

    op.create_table(
        "audit_log",
        sa.Column("audit_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("table_name", sa.String(64), nullable=False),
        sa.Column("record_id", mysql.BIGINT(unsigned=True)),
        sa.Column("action", sa.String(32), nullable=False),
        sa.Column("old_value", sa.Text),
        sa.Column("new_value", sa.Text),
        sa.Column("changed_by_id", mysql.BIGINT(unsigned=True)),
        sa.Column("changed_at", mysql.TIMESTAMP, nullable=False,
                  server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.ForeignKeyConstraint(["changed_by_id"], ["users.user_id"],
                                name="fk_audit_user", ondelete="SET NULL"),
        mysql_engine="InnoDB",
    )
    op.create_index("idx_audit_table_record", "audit_log", ["table_name", "record_id"])
    op.create_index("idx_audit_changed_at", "audit_log", ["changed_at"])

    op.create_table(
        "reservations",
        sa.Column("reservation_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("member_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("book_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("request_date", sa.Date, nullable=False),
        sa.Column("expiry_date", sa.Date),
        sa.Column("reservation_status",
                  sa.Enum("pending", "ready", "fulfilled", "cancelled", "expired",
                          name="reservation_status"),
                  nullable=False, server_default=sa.text("'pending'")),
        sa.Column("notes", sa.String(500)),
        _ts(), _ts_updated(),
        sa.ForeignKeyConstraint(["member_id"], ["members.member_id"],
                                name="fk_reservations_member", ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["book_id"], ["books.book_id"],
                                name="fk_reservations_book", ondelete="RESTRICT"),
        mysql_engine="InnoDB",
    )

    op.create_table(
        "fines",
        sa.Column("fine_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("loan_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("member_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("fine_type",
                  sa.Enum("late_return", "lost_copy", "damage", "other", name="fine_type"),
                  nullable=False),
        sa.Column("fine_amount", sa.DECIMAL(12, 2), nullable=False),
        sa.Column("assessed_date", sa.Date, nullable=False),
        sa.Column("paid_status",
                  sa.Enum("unpaid", "partial", "paid", "waived", name="fine_paid_status"),
                  nullable=False, server_default=sa.text("'unpaid'")),
        sa.Column("note", sa.String(500)),
        _ts(), _ts_updated(),
        sa.ForeignKeyConstraint(["loan_id"], ["loans.loan_id"],
                                name="fk_fines_loan", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["members.member_id"],
                                name="fk_fines_member", ondelete="RESTRICT"),
        mysql_engine="InnoDB",
    )

    op.create_table(
        "payments",
        sa.Column("payment_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("fine_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("payment_date", sa.Date, nullable=False),
        sa.Column("amount", sa.DECIMAL(12, 2), nullable=False),
        sa.Column("payment_method",
                  sa.Enum("cash", "card", "bank_transfer", "e_wallet", "other", name="payment_method"),
                  nullable=False, server_default=sa.text("'cash'")),
        sa.Column("transaction_ref", sa.String(128)),
        sa.Column("note", sa.String(500)),
        _ts(),
        sa.ForeignKeyConstraint(["fine_id"], ["fines.fine_id"],
                                name="fk_payments_fine", ondelete="CASCADE"),
        mysql_engine="InnoDB",
    )

    op.create_table(
        "sync_logs",
        sa.Column("sync_log_id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True),
        sa.Column("source_name", sa.String(64), nullable=False,
                  server_default=sa.text("'openlibrary'")),
        sa.Column("endpoint_name", sa.String(128), nullable=False),
        sa.Column("source_key", sa.String(128)),
        sa.Column("request_url", sa.String(1000), nullable=False),
        sa.Column("response_status", mysql.SMALLINT(unsigned=True)),
        sa.Column("rows_upserted", mysql.INTEGER(unsigned=True),
                  nullable=False, server_default=sa.text("0")),
        sa.Column("sync_status",
                  sa.Enum("running", "success", "failed", "partial", name="sync_status"),
                  nullable=False, server_default=sa.text("'running'")),
        sa.Column("error_message", sa.Text),
        sa.Column("started_at", mysql.TIMESTAMP, nullable=False,
                  server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column("finished_at", mysql.TIMESTAMP),
        mysql_engine="InnoDB",
    )


def downgrade() -> None:
    op.drop_table("sync_logs")
    op.drop_table("payments")
    op.drop_table("fines")
    op.drop_table("reservations")
    op.drop_index("idx_audit_changed_at", table_name="audit_log")
    op.drop_index("idx_audit_table_record", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("idx_loans_approval_status", table_name="loans")
    op.drop_index("idx_loans_requested_book", table_name="loans")
    op.drop_index("idx_loans_copy", table_name="loans")
    op.drop_index("idx_loans_member", table_name="loans")
    op.drop_table("loans")
    op.drop_table("users")
    op.drop_table("copies")
    op.drop_table("members")
    op.drop_table("editions")
    op.drop_table("book_authors")
    op.drop_table("books")
    op.drop_table("authors")
